### PR TITLE
feat: add responsive

### PR DESCRIPTION
**Pull request by jarrisondev**
__Before:__

image

__After:__

image

### CODE REVIEW

**Comment by jarrisondev** [comment]
@afordigital Check it out <3

**Comment by afordigital** [comment]
@all-contributors please add @jarrisondev for code

**Comment by afordigital** [comment]
@all-contributors please add @jarrisondev for code

**Comment by jarrisondev** [comment]
:(

**Comment by afordigital** [comment]
@all-contributors please add @jarrisondev for code

**Comment by afordigital** [comment]
https://github.com/all-contributors please add @jarrisondev for code

**Comment by afordigital** [comment]
https://github.com/all-contributors please add @jarrisondev for code

**Comment by afordigital** [comment]
@all-contributors please add @jarrisondev for code

**Comment by jarrisondev** [comment]
🫠

**Pull request merged**
